# Generated by Django 5.1.2 on 2025-04-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_ticketorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='excursionorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='excursionorder',
            name='time',
        ),
        migrations.AddField(
            model_name='excursionorder',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='theatre.excursionslot'),
        ),
    ]
